"""add_permissions_and_ci_table

Revision ID: 7546a7485374
Revises: b66820b6bda2
Create Date: 2026-07-23 21:07:58.837430

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7546a7485374'
down_revision: Union[str, Sequence[str], None] = 'b66820b6bda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicacoes_internas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_ci', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('permissions', sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'permissions')
    op.drop_table('comunicacoes_internas')
    # ### end Alembic commands ###
