"""add_ci_v2_columns

Revision ID: 995701902ab4
Revises: 7546a7485374
Create Date: 2026-07-24 11:39:17.703571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995701902ab4'
down_revision: Union[str, Sequence[str], None] = '7546a7485374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comunicacoes_internas', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('comunicacoes_internas', sa.Column('de', sa.String(length=255), nullable=True))
    op.add_column('comunicacoes_internas', sa.Column('para', sa.String(length=255), nullable=True))
    op.add_column('comunicacoes_internas', sa.Column('nome_signatario', sa.String(length=255), nullable=True))
    op.add_column('comunicacoes_internas', sa.Column('sobrenome_signatario', sa.String(length=255), nullable=True))
    op.add_column('comunicacoes_internas', sa.Column('cargo_signatario', sa.String(length=255), nullable=True))

    op.execute("UPDATE comunicacoes_internas SET tipo = 'comunicacao_interna', de = '', para = ''")

    op.alter_column('comunicacoes_internas', 'tipo', nullable=False)
    op.alter_column('comunicacoes_internas', 'de', nullable=False)
    op.alter_column('comunicacoes_internas', 'para', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comunicacoes_internas', 'cargo_signatario')
    op.drop_column('comunicacoes_internas', 'sobrenome_signatario')
    op.drop_column('comunicacoes_internas', 'nome_signatario')
    op.drop_column('comunicacoes_internas', 'para')
    op.drop_column('comunicacoes_internas', 'de')
    op.drop_column('comunicacoes_internas', 'tipo')
    # ### end Alembic commands ###
