"""alter_quantidade_participantes_to_integer

Revision ID: b0c7b9d89c5c
Revises: 2760e435dafc
Create Date: 2026-07-21 10:22:04.826675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c7b9d89c5c'
down_revision: Union[str, Sequence[str], None] = '2760e435dafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'quantidade_participantes',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='quantidade_participantes::integer')
    op.drop_constraint(op.f('usuarios_login_key'), 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=False)
    op.create_unique_constraint(op.f('usuarios_login_key'), 'usuarios', ['login'], postgresql_nulls_not_distinct=False)
    op.alter_column('agendamentos', 'quantidade_participantes',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
