"""add_role_column_to_usuarios

Revision ID: b66820b6bda2
Revises: b0c7b9d89c5c
Create Date: 2026-07-22 10:25:07.699395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66820b6bda2'
down_revision: Union[str, Sequence[str], None] = 'b0c7b9d89c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('usuarios', sa.Column('role', sa.String(length=30), nullable=True))
    op.execute("UPDATE usuarios SET role = 'superintendente' WHERE role IS NULL")
    op.alter_column('usuarios', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
